name: Release

## This workflow is limited only when a new tag is created
on:
  push:
    tags: ["*"]

## Set permissions to the github token
## https://github.com/softprops/action-gh-release#permissions 
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn run build
      - run: yarn run release
      - run: yarn run pack:icons
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
            name: icons
            path: icons.zip
            retention-days: 1

  release:
    if: ${{ github.repository == 'jmjuanes/icons' }}
    runs-on: ubuntu-latest
    name: Release
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: icons
      - uses: softprops/action-gh-release@v1
        with:
          files: icons.zip
  
  publish:
    if: ${{ github.repository == 'jmjuanes/icons' }}
    runs-on: ubuntu-latest
    name: Publish packages
    needs: [build]
    strategy:
      matrix:
        package: [svg, react]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - run: cd packages/${{ matrix.package }} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
